export default {
    wifi: "WIFI",
    sms: "SMS",
    time_settings: "TIME SETTINGS",
    zone_settings: "ZONE SETTINGS",
    zone_state: "ZONE STATE",
    output_settings: "OUTPUT SETTINGS",
    alarm_period: "ALARM PERIOD",
    system_mode: "SYSTEM MODE",
    tell_settings: "TELL SETTINGS",
    gsm_settings: "GSM SETTINGS",
    gsm_number_control: "GSM NUMBER CONTROL",
    change_menu_password: "CHANGE MENU PASSWORD",
    change_sms_password: "CHANGE SMS PASSWORD",
}