export default {
    zones_settings: "ZONE SETTINGS",
    zones_status: "ZONE STATUS",
    zone_number: "Zone {{number}}",
    wireless: "Wireless",
    wired: "Wired",
    functional_status: "Functional Status",
    zone_type: "Zone Type",
    operating_status: "Operating Status",
    fire: "Fire",
    h24: "24H",
    ordinary: "Ordinary",
    open: "Open",
    close: "Close",
    output_type: "Output Type",
    ding_dong: "Ding Dong",
    speaker: "Speaker",
    siren: "Siren",
    call: "Call",
    sms: "SMS",
}