export default {
    zones_settings: "تنظیمات زون ها",
    zones_status: "وضعیت زون ها",
    zone_number: "زون {{number}}",
    wireless: "بی سیم",
    wired: "سیمی",
    functional_status: "وضعیت عملکردی",
    zone_type: "نوع زون",
    operating_status: "وضعیت کارکرد",
    fire: "آتش",
    h24: "۲۴‌ساعته",
    ordinary: "معمولی",
    open: "باز",
    close: "بسته",
    output_type: "نوع خروجی",
    ding_dong: "دینگ دانگ",
    speaker: "بلندگو",
    siren: "آژیر",
    call: "تماس",
    sms: "پیامک",
}