export default {
    name_validation: "وارد کردن نام اجباری می باشد!",
    unique_validation: "نام دستگاه نمیتواند تکراری باشد.",
    count_validation: "لطفا تعداد دستگاه را وارد کنید.",
    min1: "۰۱ دقیقه",
    min3: "۰۳ دقیقه",
    min5: "۰۵ دقیقه",
    min15: "۱۵ دقیقه",
    min30: "۳۰ دقیقه",
    hour1: "۰۱ ساعت",
    hour2: "۰۲ ساعت",
    hour6: "۰۶ ساعت",
    hour12: "۱۲ ساعت",
    hour24: "۲۴ ساعت",
    devices_management: "مدیریت دستگاه ها",
    device_settings: "تنظیمات دستگاه ها",
    sample_rate: "نرخ داده برداری",
    summer: "تابستانه",
    winter: "زمستانه",
    wifi: "وای فای",
    group_select: "انتخاب گروهی",
    empty: "شما در حال حاضر دستگاهی ندارید.",
    add_device: "افزودن دستگاه"
}