export default {
    name_validation: "Please enter device name.",
    unique_validation: "The device name must be unique.",
    count_validation: "Please enter devices count.",
    min1: "1 minute",
    min3: "3 minutes",
    min5: "5 minutes",
    min15: "15 minutes",
    min30: "30 minutes",
    hour1: "1 hour",
    hour2: "2 hours",
    hour6: "6 hours",
    hour12: "12 hours",
    hour24: "24 hours",
    devices_management: "Devices management",
    device_settings: "Device settings",
    sample_rate: "Data aquisition rate",
    summer: "Summer mode",
    wifi: "wifi",
    group_select: "Group selection",
    empty: "You currently do not have a device.",
    add_device: "Add device",
}